version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10
    groups:
      vault/api/auth:
        patterns:
          - "github.com/hashicorp/vault/api/auth/aws"
          - "github.com/hashicorp/vault/api/auth/azure"
          - "github.com/hashicorp/vault/api/auth/gcp"
          - "github.com/hashicorp/vault/api/auth/kubernetes"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10
