version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10
    groups:
      vault/api/auth:
        patterns:
          - "github.com/hashicorp/vault/api/auth/*"
      github.com/aws/aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10
