run:
  timeout: 10m

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bank-vaults/vault-sdk)
  goimports:
    local-prefixes: github.com/bank-vaults/vault-sdk
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    # require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    confidence: 0

linters:
  enable:
    - gci
    - goimports
    - misspell
    - nolintlint
    - revive
