services:
  vault:
    container_name: internal-vault
    image: hashicorp/vault:1.14.1
    ports:
      - 127.0.0.1:8200:8200
    environment:
      SKIP_SETCAP: "true"
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_TOKEN: 227e1cce-6bf7-30bb-2d2a-acc854318caf
      VAULT_DEV_ROOT_TOKEN_ID: 227e1cce-6bf7-30bb-2d2a-acc854318caf

  bao:
    container_name: internal-bao
    image: openbao/openbao:latest
    ports:
      - 127.0.0.1:8300:8200
    environment:
      SKIP_SETCAP: "true"
      BAO_ADDR: http://127.0.0.1:8200
      BAO_TOKEN: 227e1cce-6bf7-30bb-2d2a-acc854318caf
      BAO_DEV_ROOT_TOKEN_ID: 227e1cce-6bf7-30bb-2d2a-acc854318caf
